//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAF.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDemo
    {
        public long ApplicationID { get; set; }
        public long DemoID { get; set; }
        public Nullable<int> OrderIndex { get; set; }
    
        public virtual Demo Demo { get; set; }
        public virtual SoftApplication SoftApplication { get; set; }
    }
}
