//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAF.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Demo
    {
        public Demo()
        {
            this.ApplicationDemos = new HashSet<ApplicationDemo>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string DemoPath { get; set; }
    
        public virtual ICollection<ApplicationDemo> ApplicationDemos { get; set; }
    }
}
