//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAF.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class SoftApplication
    {
        public SoftApplication()
        {
            this.ApplicationDemos = new HashSet<ApplicationDemo>();
            this.ApplicationDocuments = new HashSet<ApplicationDocument>();
            this.Features = new HashSet<Feature>();
        }
    
        public long ID { get; set; }
        public string Title { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ImagePath { get; set; }
    
        public virtual ICollection<ApplicationDemo> ApplicationDemos { get; set; }
        public virtual ICollection<ApplicationDocument> ApplicationDocuments { get; set; }
        public virtual ICollection<Feature> Features { get; set; }
    }
}
